feat: fold all HCLOUD_TOKEN handling into this action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,15 +4,28 @@ inputs:
   tps-url:
     description: TPS endpoint URL
     default: https://tps.hc-integrations.de/
+  token:
+    description: Static HCLOUD_TOKEN, will be used if provided, otherwise a token will be fetched from TPS.
 runs:
   using: composite
   steps:
     - run: |
-        ci_token=$(curl --fail --retry 2 -s \
+        token="${{ inputs.token }}"
+
+        if [[ -z "$token" ]]; then
+          # Static HCLOUD_TOKEN not provided, fetch a token from TPS.
+          ci_token=$(curl --fail --retry 2 -s \
             -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
             "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=tps" \
             | jq -r .value)
-        token="$(curl --fail --retry 2 -s -X POST -H "Authorization: Bearer $ci_token" ${{ inputs.tps-url }})"
+          token="$(curl --fail --retry 2 -s -X POST -H "Authorization: Bearer $ci_token" ${{ inputs.tps-url }})"
+        fi
+
+        if [[ "${token:-}" == "" ]]; then
+          echo "::error ::Couldn't determine HCLOUD_TOKEN. Are repository secrets correctly set?"
+          exit 1
+        fi
+
         echo "::add-mask::$token"
         echo "HCLOUD_TOKEN=$token" >> "$GITHUB_ENV"
-      shell: bash
+     shell: bash
